name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: conda-forge
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      shell: bash
      run: |
        python --version
        conda env create -f environment.yml

    - name: Install Our Package
      shell: bash
      run: |
        source activate geosci-labs
        conda install pytest
        pip install testipynb
        conda list

    - name: Run Tests
      shell: bash
      run: |
        source activate geosci-labs
        pytest .
